module.exports = {
  KOREAI_WEBHOOK_URL: 'KOREAI_WEBHOOK_URL',
  KOREAI_WEBHOOK_CLIENTID: 'KOREAI_WEBHOOK_CLIENTID',
  KOREAI_WEBHOOK_CLIENTSECRET: 'KOREAI_WEBHOOK_CLIENTSECRET',
  KOREAI_WEBHOOK_FROMID: 'KOREAI_WEBHOOK_FROMID',
  KOREAI_WEBHOOK_TOID: 'KOREAI_WEBHOOK_TOID',
  KOREAI_WEBHOOK_NLP_ANALYTICS_ENABLE: 'KOREAI_WEBHOOK_NLP_ANALYTICS_ENABLE',
  KOREAI_WEBHOOK_NLP_ANALYTICS_URL: 'KOREAI_WEBHOOK_NLP_ANALYTICS_URL',
  KOREAI_WEBHOOK_BOTNAME: 'KOREAI_WEBHOOK_BOTNAME',
  KOREAI_WEBHOOK_ADMIN_CLIENTID: 'KOREAI_WEBHOOK_ADMIN_CLIENTID',
  KOREAI_WEBHOOK_ADMIN_CLIENTSECRET: 'KOREAI_WEBHOOK_ADMIN_CLIENTSECRET'
}
