module.exports = {
  // Webhook, Web/Mobile Client
  KOREAI_WEBHOOK_CHANNEL: 'KOREAI_WEBHOOK_CHANNEL',
  KOREAI_WEBHOOK_BASE_URL: 'KOREAI_WEBHOOK_BASE_URL',
  KOREAI_WEBHOOK_BOTID: 'KOREAI_WEBHOOK_BOTID',
  KOREAI_WEBHOOK_BOTNAME: 'KOREAI_WEBHOOK_BOTNAME',
  KOREAI_WEBHOOK_CLIENTID: 'KOREAI_WEBHOOK_CLIENTID',
  KOREAI_WEBHOOK_CLIENTSECRET: 'KOREAI_WEBHOOK_CLIENTSECRET',
  KOREAI_WEBHOOK_NLP_ANALYTICS_ENABLE: 'KOREAI_WEBHOOK_NLP_ANALYTICS_ENABLE',
  KOREAI_WEBHOOK_URL: 'KOREAI_WEBHOOK_URL',
  // advanced cap
  KOREAI_WEBHOOK_NLP_ANALYTICS_URL: 'KOREAI_WEBHOOK_NLP_ANALYTICS_URL',
  // Just for NLP
  KOREAI_WEBHOOK_FROMID: 'KOREAI_WEBHOOK_FROMID',
  KOREAI_WEBHOOK_TOID: 'KOREAI_WEBHOOK_TOID',
  KOREAI_WEBHOOK_ADMIN_CLIENTID: 'KOREAI_WEBHOOK_ADMIN_CLIENTID',
  KOREAI_WEBHOOK_ADMIN_CLIENTSECRET: 'KOREAI_WEBHOOK_ADMIN_CLIENTSECRET',
  KOREAI_WEBHOOK_WELCOME_TEXT: 'KOREAI_WEBHOOK_WELCOME_TEXT',
  // optional webhook payload extension
  KOREAI_WEBHOOK_CUSTOMDATA: 'KOREAI_WEBHOOK_CUSTOMDATA',
  KOREAI_WEBHOOK_CUSTOMDATA_MODE: 'KOREAI_WEBHOOK_CUSTOMDATA_MODE',
  // IVR-specific capabilities
  KOREAI_WEBHOOK_IVR_DNIS: 'KOREAI_WEBHOOK_IVR_DNIS',
  KOREAI_WEBHOOK_IVR_DOMAIN: 'KOREAI_WEBHOOK_IVR_DOMAIN',
  KOREAI_WEBHOOK_IVR_ANI: 'KOREAI_WEBHOOK_IVR_ANI'
}
